<#
    Shared Reporting Module for IdentityFirst QuickChecks
    Provides consistent JSON and HTML output across all modules
#>

function Export-IdentityReport {
    param(
        [Parameter(Mandatory)]
        [string]$ModuleName,
        
        [Parameter(Mandatory)]
        [string]$CheckName,
        
        [Parameter(Mandatory)]
        [object]$Data,
        
        [string]$OutputPath = "."
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
    $baseName = "$ModuleName-$CheckName-$timestamp"
    
    # Export JSON
    $jsonPath = Join-Path $OutputPath "$baseName.json"
    $report = @{
        module = $ModuleName
        check = $CheckName
        timestamp = (Get-Date).ToString("o")
        count = ($Data | Measure-Object).Count
        data = $Data
    }
    $report | ConvertTo-Json -Depth 10 | Out-File -FilePath $jsonPath -Encoding UTF8
    
    # Export HTML
    $htmlPath = Join-Path $OutputPath "$baseName.html"
    $htmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <title>IdentityFirst - $ModuleName Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #1a73e8; }
        h2 { color: #5f6368; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #1a73e8; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .meta { color: #666; font-size: 0.9em; margin-bottom: 20px; }
        .count { font-weight: bold; color: #1a73e8; }
    </style>
</head>
<body>
    <h1>IdentityFirst $ModuleName</h1>
    <div class="meta">
        <p><strong>Check:</strong> $CheckName</p>
        <p><strong>Generated:</strong> $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
        <p><strong>Records:</strong> <span class="count">$($report.count)</span></p>
    </div>
    <h2>Results</h2>
    TABLE_PLACEHOLDER
    <footer>
        <p><em>Generated by IdentityFirst QuickChecks. For full analysis, run IdentityHealthCheck.</em></p>
    </footer>
</body>
</html>
"@
    
    # Generate HTML table from data
    if ($Data -and ($Data | Measure-Object).Count -gt 0) {
        $htmlTable = "<table><tr>"
        $properties = $Data[0].PSObject.Properties.Name
        foreach ($prop in $properties) {
            $htmlTable += "<th>$prop</th>"
        }
        $htmlTable += "</tr>"
        
        foreach ($item in $Data) {
            $htmlTable += "<tr>"
            foreach ($prop in $properties) {
                $value = $item.$prop
                if ($null -eq $value) { $value = "" }
                $htmlTable += "<td>$value</td>"
            }
            $htmlTable += "</tr>"
        }
        $htmlTable += "</table>"
        $htmlContent = $htmlContent.Replace("TABLE_PLACEHOLDER", $htmlTable)
    } else {
        $htmlContent = $htmlContent.Replace("TABLE_PLACEHOLDER", "<p>No results found.</p>")
    }
    
    $htmlContent | Out-File -FilePath $htmlPath -Encoding UTF8
    
    return @{
        JsonPath = $jsonPath
        HtmlPath = $htmlPath
        RecordCount = $report.count
    }
}

function Write-IdentityHeader {
    param(
        [string]$Title,
        [string]$Description
    )
    
    Write-Host ""
    Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  $Title" -ForegroundColor White -BackgroundColor DarkBlue
    Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    if ($Description) {
        Write-Host "  $Description" -ForegroundColor Gray
    }
    Write-Host ""
}

function Write-IdentityResult {
    param(
        [int]$Count,
        [string]$Context = "results"
    )
    
    if ($Count -gt 0) {
        Write-Host "  ⚠ Found $Count $context" -ForegroundColor Yellow
    } else {
        Write-Host "  ✓ No issues detected" -ForegroundColor Green
    }
}

function Get-ReferToIHC {
    return @"

  ─────────────────────────────────────────────────────────────
  ℹ  For full analysis, governance review, and compliance 
     assessment, run IdentityHealthCheck.
  ─────────────────────────────────────────────────────────────
"@
}

Export-ModuleMember -Function Export-IdentityReport, Write-IdentityHeader, 
                            Write-IdentityResult, Get-ReferToIHC
